CREATE TABLE admin_actions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL
);
CREATE TABLE contributions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'inactive'
);
CREATE TABLE contributions_rules
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    rule_id INT NOT NULL,
    contribution_id INT UNSIGNED NOT NULL
);
CREATE TABLE contributions_settings
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    contribution_id INT NOT NULL,
    rule_id INT NOT NULL,
    `key` VARCHAR(150) NOT NULL,
    value VARCHAR(150) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE cooperators
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED,
    employee_id VARCHAR(50) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    branch VARCHAR(100) NOT NULL,
    date_joined_company DATETIME,
    date_approved DATETIME NOT NULL,
    home_address VARCHAR(100) NOT NULL,
    home_town VARCHAR(100) NOT NULL
);
CREATE TABLE cooperators_bank_accounts
(
    id INT PRIMARY KEY NOT NULL,
    cooperator_id INT NOT NULL,
    bank VARCHAR(50) NOT NULL,
    acount_name VARCHAR(70) NOT NULL,
    account_number VARCHAR(70) NOT NULL,
    branch VARCHAR(70) NOT NULL
);
CREATE TABLE cooperators_contributions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cooperator_id INT NOT NULL,
    contribution_id INT UNSIGNED NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE cooperators_groups
(
    id INT PRIMARY KEY NOT NULL,
    cooperator_id INT NOT NULL,
    group_id INT NOT NULL
);
CREATE TABLE groups
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(225) NOT NULL,
    status VARCHAR(20) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by INT UNSIGNED
);
CREATE TABLE loans
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(50),
    description VARCHAR(500),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE loans_rules
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    rule_id INT NOT NULL,
    loan_id INT NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE loans_settings
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    loan_id INT NOT NULL,
    br_id INT NOT NULL,
    `key` VARCHAR(50) NOT NULL,
    value VARCHAR(150) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE messages
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    subject VARCHAR(50) NOT NULL,
    message VARCHAR(1500) NOT NULL,
    date_sent DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL
);
CREATE TABLE next_of_kin
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cooperator_id INT NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    relationship VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    `Column 9` VARCHAR(50) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE permissions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE roles
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE roles_permissions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    role_id INT UNSIGNED NOT NULL,
    permission_id INT UNSIGNED NOT NULL
);
CREATE TABLE rule_definitions
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    rule_id INT,
    rules_def VARCHAR(1500)
);
CREATE TABLE rules
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE rules_settings
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    rule_id INT NOT NULL,
    `key` VARCHAR(50) NOT NULL,
    value VARCHAR(150) NOT NULL
);
CREATE TABLE settings
(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(255) DEFAULT '0',
    value VARCHAR(255) DEFAULT '0'
);
CREATE TABLE transaction_types
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(20),
    description VARCHAR(500),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE transactions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    transaction_type VARCHAR(20),
    amount DECIMAL(10,0),
    cooperator_id INT NOT NULL,
    loan_id INT,
    contribution_id INT UNSIGNED,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE user_actions
(
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    changed_by INT UNSIGNED NOT NULL,
    action_performed VARCHAR(200) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE user_messages
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    sender_id INT UNSIGNED,
    receipient_id INT UNSIGNED,
    message_id INT UNSIGNED,
    date_sent TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE user_roles
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    role_id INT UNSIGNED NOT NULL
);
CREATE TABLE users
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    passwd VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active BIT DEFAULT b'0' NOT NULL,
    last_login VARCHAR(25) NOT NULL
);
CREATE TABLE users_permissions
(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    permissionsTitle VARCHAR(255) NOT NULL
);
ALTER TABLE contributions_rules ADD FOREIGN KEY ( contribution_id ) REFERENCES contributions ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE contributions_rules ADD FOREIGN KEY ( rule_id ) REFERENCES loans ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX unique_id ON contributions_settings ( id );
CREATE UNIQUE INDEX unique_key ON contributions_settings ( `key` );
ALTER TABLE cooperators ADD FOREIGN KEY ( user_id ) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cooperators_bank_accounts ADD FOREIGN KEY ( cooperator_id ) REFERENCES cooperators ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cooperators_contributions ADD FOREIGN KEY ( contribution_id ) REFERENCES contributions ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cooperators_contributions ADD FOREIGN KEY ( cooperator_id ) REFERENCES cooperators ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cooperators_groups ADD FOREIGN KEY ( cooperator_id ) REFERENCES cooperators ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cooperators_groups ADD FOREIGN KEY ( group_id ) REFERENCES groups ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE groups ADD FOREIGN KEY ( created_by ) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE loans_rules ADD FOREIGN KEY ( loan_id ) REFERENCES loans ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE loans_rules ADD FOREIGN KEY ( rule_id ) REFERENCES rules ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE loans_settings ADD FOREIGN KEY ( br_id ) REFERENCES rules ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE loans_settings ADD FOREIGN KEY ( loan_id ) REFERENCES loans ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE next_of_kin ADD FOREIGN KEY ( cooperator_id ) REFERENCES cooperators ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE roles_permissions ADD FOREIGN KEY ( permission_id ) REFERENCES permissions ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE roles_permissions ADD FOREIGN KEY ( role_id ) REFERENCES roles ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE rule_definitions ADD FOREIGN KEY ( rule_id ) REFERENCES rules ( id );
ALTER TABLE rules_settings ADD FOREIGN KEY ( rule_id ) REFERENCES rules ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX `key` ON rules_settings ( `key` );
ALTER TABLE transactions ADD FOREIGN KEY ( contribution_id ) REFERENCES contributions ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE transactions ADD FOREIGN KEY ( cooperator_id ) REFERENCES cooperators ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE transactions ADD FOREIGN KEY ( loan_id ) REFERENCES loans ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_actions ADD FOREIGN KEY ( changed_by ) REFERENCES users ( id );
CREATE INDEX FK_admin_actions_user_actions ON user_actions ( action_performed );
ALTER TABLE user_messages ADD FOREIGN KEY ( message_id ) REFERENCES messages ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_messages ADD FOREIGN KEY ( receipient_id ) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_messages ADD FOREIGN KEY ( sender_id ) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_roles ADD FOREIGN KEY ( role_id ) REFERENCES roles ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE user_roles ADD FOREIGN KEY ( user_id ) REFERENCES users ( id ) ON DELETE CASCADE ON UPDATE CASCADE;
